import Link from "next/link"
import type { ReactNode } from "react"

const hostCommand =
  "pnpx @skxv/oct-daemon --workspace /path/to/workspace --server https://oct.skxv.dev"

const syncCommand =
  "pnpx @skxv/oct-daemon@latest sync --room your-room-key --workspace /path/to/workspace --server https://oct.skxv.dev"

const defaultExcludes =
  "**/.env\n.git/**\nnode_modules/**\n.opencollabtools-daemon/**\n.opencollabtools-sync/**"

const hostOptions = [
  ["--workspace <path>", "Folder to share. This is required for host mode."],
  [
    "--server <url>",
    "OCT server URL. Defaults to https://api.open-collab.tools/.",
  ],
  ["--auth-token <token>", "Reusable OCT login token."],
  [
    "--auth-token-file <path>",
    "Token file. Defaults to <workspace>/.opencollabtools-daemon/auth-token.",
  ],
  ["--readonly", "Reject write operations from guests."],
  ["--exclude <glob>", "Repeatable exclude glob."],
  ["--name <name>", "Workspace display name. Defaults to the folder basename."],
  ["-d, --detached", "Run the daemon in the background."],
]

const syncOptions = [
  ["sync --room <code>", "Room code to join. This is required for sync mode."],
  ["sync --workspace <path>", "Local folder to synchronize."],
  [
    "sync --server <url>",
    "OCT server URL. Defaults to https://api.open-collab.tools/.",
  ],
  ["sync --auth-token <token>", "Reusable OCT login token."],
  ["sync --auth-token-file <path>", "Token file for the local sync client."],
  ["sync --exclude <glob>", "Repeatable exclude glob."],
]

function CommandBlock({ children }: { children: ReactNode }) {
  return (
    <pre className="overflow-x-auto rounded-lg border border-doc-code-border bg-doc-code p-4 font-mono text-[0.84rem] leading-6 text-doc-code-text">
      <code className="bg-doc-code">{children}</code>
    </pre>
  )
}

function OptionList({ options }: { options: string[][] }) {
  return (
    <div className="divide-y divide-doc-divider border-y border-doc-divider">
      {options.map(([name, description]) => (
        <div
          key={name}
          className="grid gap-2 py-4 sm:grid-cols-[210px_1fr] sm:gap-6"
        >
          <code className="font-mono text-[0.82rem] text-doc-code-text">
            {name}
          </code>
          <p className="text-[1rem] leading-7 text-page-body">{description}</p>
        </div>
      ))}
    </div>
  )
}

export default function ReadMorePage() {
  return (
    <main className="min-h-svh bg-background px-5 py-14 text-foreground sm:px-8 sm:py-20">
      <article className="mx-auto flex w-full max-w-[760px] flex-col gap-14">
        <header className="flex flex-col gap-8">
          <Link
            href="/"
            className="inline-flex w-fit items-center text-sm font-medium text-page-body transition hover:text-foreground"
          >
            <span aria-hidden="true" className="mr-2">
              &lt;-
            </span>{" "}
            Back
          </Link>
          <div>
            <p className="text-sm font-medium text-page-host">oct-daemon</p>
            <h1 className="mt-2 text-[2rem] leading-tight font-medium text-page-heading sm:text-[2.6rem]">
              Host and sync OCT workspaces from the command line.
            </h1>
          </div>
          <p className="max-w-[650px] text-[1.08rem] leading-8 text-page-body sm:text-[1.16rem]">
            oct-daemon wraps Open Collaboration Tools in a CLI that can either
            host a local folder as a room or join a room and mirror it into a
            local directory. The same package handles both flows.
          </p>
        </header>

        <section id="host-mode" className="flex scroll-mt-10 flex-col gap-5">
          <h2 className="text-[1.4rem] leading-tight font-medium text-page-heading">
            Host mode
          </h2>
          <CommandBlock>{hostCommand}</CommandBlock>
          <div className="space-y-5 text-[1.04rem] leading-8 text-page-body">
            <p>
              Host mode creates a new OCT room, exposes the selected workspace,
              accepts joins, and serves filesystem operations for connected
              clients. The daemon prints a generated room ID and join URI when
              the room is ready.
            </p>
            <p>
              Room IDs are generated by the OCT server. A caller-chosen room
              code is not supported in v1.
            </p>
          </div>
          <OptionList options={hostOptions} />
        </section>

        <section id="sync-mode" className="flex scroll-mt-10 flex-col gap-5">
          <h2 className="text-[1.4rem] leading-tight font-medium text-page-heading">
            Sync mode
          </h2>
          <CommandBlock>{syncCommand}</CommandBlock>
          <div className="space-y-5 text-[1.04rem] leading-8 text-page-body">
            <p>
              Sync mode joins an existing room and keeps a local folder aligned
              with the remote workspace. It downloads the room contents first,
              then watches local filesystem changes and pushes creates, edits,
              and deletes back to the room host.
            </p>
            <p>
              Incoming collaborator changes are written back into the same local
              folder, which makes the command useful when an agent needs normal
              file access while staying attached to a live OCT room.
            </p>
          </div>
          <OptionList options={syncOptions} />
        </section>

        <section className="flex flex-col gap-5 pb-10">
          <h2 className="text-[1.4rem] leading-tight font-medium text-page-heading">
            Default excludes
          </h2>
          <p className="text-[1.04rem] leading-8 text-page-body">
            oct-daemon ignores common private, generated, and metadata paths by
            default.
          </p>
          <CommandBlock>{defaultExcludes}</CommandBlock>
        </section>
      </article>
    </main>
  )
}
